Pipfile
Pipfile.lock
preventionpoint/settings.py
preventionpoint/urls.py
step/models.py
step/urls.py
step/views.py

working /api/token and /api/token/refresh endpoints

Start auth

---

frontend/.stylelintrc
frontend/src/components/ParticipantSearch.js
frontend/src/components/Root.js
frontend/src/index.js
frontend/src/scss/participant-search.scss

Still need to figure out how we want to dynamically render components/pages but this is the first start on the Participant Search component

Add participant search component

---

Pipfile
Pipfile.lock
preventionpoint/urls.py
step/employee_roles/serializers.py
step/employee_roles/views.py
step/employees/serializers.py
step/employees/views.py
step/models.py

Employee api

---

frontend/.eslintrc.json
frontend/devServer.js
frontend/package.json
frontend/yarn.lock

Calls to the frontend development server's /api path will proxy to the backend development server

Configure frontend server for local development

---

frontend/README.md
frontend/package.json
frontend/yarn.lock

Add Mobx for state management

---

.travis.yml
frontend/.babelrc
frontend/.eslintrc.json
frontend/package.json
frontend/src/App.js
frontend/src/index.js
frontend/src/routes/index.js
frontend/src/setupTests.js
frontend/test/App.test.js
frontend/test/__mocks__/fileMock.js
frontend/yarn.lock

Set up frontend testing with Jest and Enzyme. Incorporate into CI.

Frontend testing

---

.travis.yml
Dockerfile
Pipfile
Pipfile.lock
README.md
docker-compose.yml
manage.py
preventionpoint/settings.py
preventionpoint/settings/common.py
preventionpoint/settings/development.py
preventionpoint/settings/test.py

This PR makes the switch from sqlite to postgres/docker-compose in development. Our unit tests will still run on django's sqlite backend because it's so convenient.
This is related to issue #62

Use Postgres

---

core/tests/visits.py

Add test to validate that certain users/groups cannot access certain endpoints

Test Authorization

---

core/tests/visits.py
core/visits/views.py

Front desk should not be able to view visits

Fix visit endpoint permissions

---

frontend/package.json
frontend/src/App.js
frontend/yarn.lock

Bump material version to 4.x. This will aid in development as we'll be able to more-quickly build off examples in Material's docs.

Bump material to v4

---

frontend/src/components/AllQueues.js
frontend/yarn.lock

Previous merge introduced a bug. AllQueues re-renders after each refresh of token.  Removed dependency array in useEffect to get rid of the error. Had to suppress eslint

Fix re-rendering from useEffect in AllQueues

---

frontend/package.json
frontend/src/api/participantEndpoints.js
frontend/src/components/UserSearch.js
frontend/yarn.lock

Filter users by search params

---

frontend/src/components/GsTitle.js

208: Modify General Services button to route to home page

---

core/tests/visits.py
core/visits/views.py

Backend updates visit for notes, urgency and program/service queue

Update visit 231

---

core/settings/docker.py
script/server
script/setup
script/update
uwsgi.ini

Build static assets and serve from uwsgi

Serve static assets in docker container

---

frontend/package.json
frontend/src/components/LoginForm.js
frontend/src/scss/login-form.scss
frontend/src/stores/AuthStore.js
frontend/yarn.lock

add UI error state when login fails; remove unused packages

---

frontend/src/components/GsTitle.js

Easy fix for https://github.com/CodeForPhilly/prevention-point/issues/278

Fix GsTitle to use react router link

---

frontend/src/components/LoginForm.js
frontend/src/components/ParticipantInfo.js
frontend/src/components/UserSearch.js

Replacing the remaining MUI Input components with the PrevPointInput.

PR269: Replacing all inputs with PrevPointInput

---

frontend/src/components/QueueComponent/QueueTable/QueueTable.js

Add wait time to particpants

---

frontend/src/components/ParticipantInfo.js
frontend/src/components/ParticipantTableComponent/PrevPointTableBody.js
frontend/src/components/PrevPointButton.js
frontend/src/stores/ParticipantStore.js
frontend/src/views/ParticipantList.js

- assign participant id to visit ajax POST, so ParticipantInfo knows there is no visit coming from ParticipantList
- move setting currentParticipant from to button in ParticipantList
- reinstate toJs on participant and visit state in ParticipantInfo (assigned below default setting 'if' statements)
- fix notes input label
- cleanup stale PrevPointButton code
i think this satisfies #280, and patches any bugs that my larger, closed PR was fixing

fix: move logic to solve some MUI select warnings

---

frontend/src/components/QueueComponent/QueueTabContent/QueueTabContent.js
frontend/src/components/QueueComponent/QueueTable/QueueTable.js
frontend/src/stores/QueueStore.js
frontend/src/views/AllQueues.js
frontend/test/AllQueues.test.js

#289 
Scaffolding out removing the dependencies on hard coded ids in the QueueStore

Dynamic Queues

---

frontend/src/components/Navbar.js

Remove alert bell

---

frontend/package.json
frontend/src/components/ParticipantTableComponent/PrevPointPagination.js
frontend/src/views/ParticipantList.js
frontend/yarn.lock

Adds the Material UI pagination component to the participant list. Fixes issue #356

Add pagination to ParticipantList

---

frontend/src/components/ParticipantForm.js
frontend/src/components/ParticipantTableComponent/PrevPointTableHead.js

Just some stuff I found going around.

Just some code cleanup

---

frontend/src/api/frontDeskEventEndpoints.js
frontend/src/stores/ParticipantStore.js

Renamed getFrontDeskEvents method to createNewFrontDeskEvents in 

---

frontend/src/components/QueueComponent/QueueTable/QueueTable.js
frontend/src/components/QueueComponent/QueueTable/QueueTableDropdown/QueueTableDropdown.js

removed sorting for Seen and Notes columns

---

core/fixtures/sep_data.yaml
core/management/commands/users_and_groups.py
core/queue/serializers.py
core/sep_data/serializers.py
core/sep_data/views.py
core/tests/__init__.py
core/tests/sep_data.py
core/urls.py

creates an endpoint to post SEP data to.
#384

SEP Data route

---

frontend/package.json
frontend/src/components/VisitRouter/index.js
frontend/src/stores/ParticipantStore.js
frontend/src/views/AllQueues.js
frontend/src/views/NewParticipantView.js
frontend/yarn.lock

- upgrade material-table to fix errors
- heed warning and check mobx array length
- remove temporary checks in forms

fix console errors and lingering obsolete logic

---

frontend/src/components/ParticipantTableComponent/PrevPointTableBody.js

Formats the date in the participant table using toLocaleDateString(). I did not see a date in the queue table.

Update date format in the participant table

---

frontend/src/components/NoResults.js
frontend/src/layouts/MainLayout.js
frontend/src/stores/ParticipantStore.js
frontend/src/views/ParticipantList.js
frontend/test/ParticipantList.test.js

No participants found display

---

frontend/src/components/SepForm.js
frontend/src/stores/ParticipantStore.js

let's be honest, mikey did all of this

fixed sepsite errors

---

frontend/src/components/SepForm.js
frontend/src/stores/ParticipantStore.js

Please note that the date value is not currently passed when calling createSEP().

SEP form date default to current day

---

frontend/src/App.js
frontend/src/components/SepForm.js
frontend/src/components/VisitRouter/index.js
frontend/src/constants/index.js
frontend/src/error/index.js
frontend/src/stores/AuthStore.js
frontend/src/stores/ParticipantStore.js
frontend/src/stores/QueueStore.js
frontend/src/stores/UtilityStore.js
frontend/src/views/ExistingParticipantView.js
frontend/src/views/NewParticipantView.js

This PR updates the Snackbar component to use MUI Alert and updates the error handling to include the severity level for the Alert component. The SEP form has also been updated to display a success message using the Snackbar and clear the form.

Issue 431 and 441 - snackbar updates

---

frontend/src/components/SepForm.js
frontend/src/stores/UtilityStore.js

@LizKalter found this, using the wrong id when populating from table. I missed it in review. The spreading out of "Other values" might be overkill, but i did not want to screw up what values are being passed to formik out of caution

use correct id for populatinon

---

frontend/test/PrevPointButton.test.js
frontend/test/__snapshots__/PrevPointButton.test.js.snap

Pretty straightforward series of tests. 
Fixes #477

Test prevpointbutton 477

---

frontend/src/api/index.js
frontend/src/api/sepEndpoints.js
frontend/src/api/siteEndpoints.js
frontend/src/components/VisitRouter/VisitData.js
frontend/src/components/VisitRouter/index.js
frontend/src/stores/ParticipantStore.js
frontend/test/ExistingParticipantView.test.js
frontend/test/VisitData.test.js

This is still kind of a work in progress, i threw it together pretty quickly, but  represents the final major feature that was missing

allow for visit data display

---

frontend/src/validation/index.js
frontend/test/VisitSchema.test.js

I think this covers everything. Let me know if it don't.
Closes #481

Yup visit schema validation testing function.

---

frontend/src/validation/index.js
frontend/test/ParticipantSchema.test.js
frontend/test/VisitSchema.test.js

Let me know if I missed anythang.
Closes #482

Test participant validation schema 482

---

frontend/test/ParticipantStore.test.js

Just testing actions and state. Decided against including any of the getter functions as many of them are tested in other UI tests.
Closes #478

Test participant store actions 478

---

frontend/.eslintrc.json
frontend/src/components/SepForm.js

PR-fixing-sep-form-hook

---

.holo/branches/helm-chart/_prevention-point.toml
.holo/config.toml

Initialize Hologit to allow for deployment to cfp-sandbox-cluster for testing.

Initialize Hologit and invoke Deploy
